- name: Windows_update
  hosts: windows_servers
  gather_facts: false
  become: true
  become_method: runas
  become_user: SYSTEM
  tasks:              
    - name: update_search
      ansible.windows.win_updates:
        category_names:
          - SecurityUpdates
          - CriticalUpdates
          - UpdateRollups
          - Updates
          - DefinitionUpdates
        state: searched
        server_selection: windows_update
      register: win_update_result

    - name: 输出Windows补丁搜索结果
      ansible.builtin.debug:
        msg: |
          ==============================================
          Windows 补丁搜索结果汇总
          ==============================================
          待安装补丁总数: {{ win_update_result.found_update_count }}
          失败补丁数量: {{ win_update_result.failed_update_count | default(0) }}
          ==============================================
          待安装补丁明细:
          {{
            win_update_result.updates
            | dict2items
            | map(attribute='value.title')
            | list
          }}
